name: Build
# This workflow is triggered on pushed to the repository
on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build Wrapper
      run: gradle wrapper
    - name: Build with Gradlew
      run: ./gradlew build
